#!/usr/bin/env python3
"""EF Qatar public home page — desktop and mobile artboards.

The mark, lockup and icon set are shared with the console design rather than
duplicated, so the two deliverables cannot drift apart.

Composition follows EF's own brand guideline: deep maroon panels carrying the
mark oversized, a green figures band lifted over the hero edge, green as the
energetic accent. Zones follow the Design Brief
(INSP-EFQatar-DESIGN-HomeAndMember-v0.1) section 6.2, with three programme
pillars, a gallery and a member quote added on top of it.

The eleven photographs are PLACEHOLDERS generated by make-placeholders.py —
defocused compositions in the brand palette, because every image host is
blocked from this environment and EF has not supplied photographs yet. Each is
labelled "placeholder" in the layout. Replacing one is a file swap: same
filename in images/, same aspect, then re-run this script.
"""
import pathlib, sys

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str((HERE / '..' / 'console').resolve()))
from build import mark, lockup, ic  # noqa: E402

MAROON, GREEN, PALE = '#4B1728', '#4BB148', '#E9F1FA'
SUPPLY = 'EF to supply'

FONTS = ('<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
         'family=Quicksand:wght@500;600;700&'
         'family=Nunito+Sans:opsz,wght@6..12,400;6..12,600;6..12,700&display=swap">')

CSS = """
    body { margin: 0; font-family: 'Nunito Sans', system-ui, sans-serif; background: #E9F1FA;
           color: #4A4045; -webkit-font-smoothing: antialiased; }
    * { box-sizing: border-box; }
    a { color: #2A7F26; text-decoration: none; }
    a:hover { color: #226520; }
    h1, h2, h3 { font-family: Quicksand, system-ui, sans-serif; color: #241017; margin: 0;
                 font-weight: 700; letter-spacing: -0.015em; }
    p { margin: 0; }
    .wrap { max-width: 1200px; margin: 0 auto; padding: 0 44px; }
    .btn { display: inline-flex; align-items: center; justify-content: center; gap: 9px;
           height: 50px; padding: 0 28px; border-radius: 8px; font-size: 15.5px;
           font-weight: 700; font-family: 'Nunito Sans', sans-serif;
           border: 1.5px solid transparent; white-space: nowrap; }
    .btn-g { background: #4BB148; color: #1E3319; }
    .btn-g:hover { background: #43A340; color: #1E3319; }
    .btn-ghost { background: transparent; color: #FFFFFF; border-color: #8A5468; }
    .btn-ghost:hover { border-color: #FFFFFF; color: #FFFFFF; }
    .btn-m { background: #4B1728; color: #FFFFFF; }
    .btn-m:hover { background: #642034; color: #FFFFFF; }
    .card { background: #FFFFFF; border: 1px solid #D8E4F0; border-radius: 14px; }
    .eyebrow { font-family: Quicksand, sans-serif; font-size: 12.5px; font-weight: 700;
               letter-spacing: 0.16em; color: #2A7F26; }
    .nav-a { font-size: 15px; font-weight: 600; color: #4A4045; }
    .nav-a:hover { color: #4B1728; }
    .tbc { display: inline-flex; align-items: center; font-family: Quicksand, sans-serif;
           font-size: 12.5px; font-weight: 700; color: #8A7F85; background: #F4F7FA;
           border: 1px dashed #C6D0DC; border-radius: 6px; padding: 5px 10px;
           white-space: nowrap; }
    .fig-tbc { font-family: Quicksand, sans-serif; font-size: 11.5px; font-weight: 700;
               color: #23431C; border: 1px dashed rgba(22, 41, 15, 0.45); border-radius: 6px;
               padding: 5px 9px; white-space: nowrap; }
    .lede { font-size: 17.5px; line-height: 1.65; color: #4A4045; text-wrap: pretty; }
    /* an image position: brand duotone, the mark as texture, caption over a scrim */
    .slot { position: relative; overflow: hidden; }
    .slot-tex { position: absolute; right: -13%; top: -20%; opacity: 0.085; }
    .slot-icon { position: absolute; inset: 0; display: flex; align-items: center;
                 justify-content: center; }
    .slot-cap { position: absolute; left: 0; right: 0; bottom: 0; padding: 15px 17px;
                display: flex; align-items: flex-end; justify-content: space-between;
                gap: 10px; background: linear-gradient(to top,
                rgba(20, 8, 12, 0.66) 0%, rgba(20, 8, 12, 0) 100%); }
    .slot-t { font-family: Quicksand, sans-serif; font-size: 14.5px; font-weight: 700;
              color: #FFFFFF; }
    .slot-chip { font-family: Quicksand, sans-serif; font-size: 10px; font-weight: 700;
                 letter-spacing: 0.06em; color: #F0E2E7;
                 border: 1px dashed rgba(255, 255, 255, 0.5); border-radius: 5px;
                 padding: 3px 7px; white-space: nowrap; }
    @keyframes floaty { 0%, 100% { transform: translateY(0); }
                        50% { transform: translateY(-9px); } }
    .float-a { animation: floaty 7s ease-in-out infinite; }
    .float-b { animation: floaty 7s ease-in-out infinite 1.4s; }
    .float-c { animation: floaty 7s ease-in-out infinite 2.8s; }
"""

TONES = {'m': ('#5E2036', '#39101F'),
         'g': ('#4AAE46', '#25691F'),
         'p': ('#96707E', '#5C3844'),
         'd': ('#2E7A2B', '#153F12')}

NAV = ['About', 'Membership', 'Events', 'News']
GATED = ['Directory', 'Jobs', 'Marketplace']

ANNOUNCEMENTS = [
    ('12 February 2027', 'Notice of the Annual General Meeting',
     "The agenda, the Treasurer's statement and the papers for the meeting are published "
     "for members."),
    ('5 February 2027', 'Renewal for 2027 opens on 1 March',
     'Members renew from their own page. Dues are QAR 500 for the year and a receipt is '
     'issued on payment.'),
    ('28 January 2027', 'Committee elected for the 2027 term',
     'The officers elected at the general meeting, and the portfolio each of them holds.'),
]

EVENTS = [('MAR', '14', 'Structural engineering seminar', '18:30'),
          ('MAR', '27', 'EF cricket tournament 2027', '07:00'),
          ('APR', '10', 'Arts evening', '19:00')]

PILLARS = [
    ('m', 'Engineering', 'Technical seminar', 'pillar-engineering.jpg',
     'Seminars and workshops across the disciplines, run by members for members, and '
     'recorded against your profile.'),
    ('g', 'Sport', 'Sports tournament', 'pillar-sport.jpg',
     'Tournaments through the season, with teams, fixtures and a waiting list when one '
     'fills. Waivers and emergency contacts held for every player.'),
    ('p', 'Arts and culture', 'Cultural evening', 'pillar-arts.jpg',
     'The evenings that make EF more than a register — music, performance and the '
     'festivals the community keeps, with families welcome.'),
]

GALLERY = [('m', 'Cultural evening', 'gallery-cultural.jpg', 'span 2 / span 2'),
           ('g', 'Cricket tournament', 'gallery-cricket.jpg', 'span 1 / span 1'),
           ('p', 'Technical seminar', 'gallery-seminar.jpg', 'span 1 / span 1'),
           ('d', 'General meeting', 'gallery-meeting.jpg', 'span 1 / span 2')]

BENEFITS = [
    ('id', 'Member Digital ID',
     'A credential you carry on your phone and a partner can check. It works without a '
     'signal, and stops working the day your membership lapses.'),
    ('cal', 'Events and programmes',
     'Seminars, workshops, sport and the arts — booked, paid and ticketed in one place, '
     'with your ticket scanned at the door.'),
    ('search', 'The member directory',
     '800 engineers, searchable by name, employer, skill and category — and you decide '
     'what of yours is visible.'),
    ('case', 'The job board',
     'Vacancies posted by members and by employers EF has authorised, each one approved '
     'before it appears.'),
    ('tag', 'Partner offers',
     'Benefits EF has negotiated on your behalf, redeemed against your membership rather '
     'than a coupon code.'),
    ('doc', 'Your documents',
     'Every invoice, receipt and credit note EF has issued you, numbered in sequence and '
     'downloadable at any time.'),
]

OFFICERS = ['President', 'Secretary', 'Treasurer', 'Technical Secretary']


def tbc(label):
    return f'<span class="tbc">{label}</span>'


def arrow(color='#2A7F26'):
    return (f'<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="{color}" '
            f'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">'
            f'<path d="M4 12h15M13 6l6 6-6 6"/></svg>')


def lock():
    return ('<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#A9A0A5" '
            'stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">'
            '<rect x="4" y="11" width="16" height="10" rx="2"/>'
            '<path d="M8 11V7a4 4 0 0 1 8 0v4"/></svg>')


def slot(tone, caption, img=None, extra='', cls='', tex=340, radius=16,
         ratio='placeholder', chip=True):
    """One image position. The duotone stays behind the photograph as its fallback."""
    a, b = TONES[tone]
    if img:
        fill = (f'<img src="{img}" alt="" style="position: absolute; inset: 0; '
                f'width: 100%; height: 100%; object-fit: cover; display: block;">')
    else:
        fill = (f'<div class="slot-tex">{mark(tex, "#FFFFFF", "#FFFFFF")}</div>'
                f'<div class="slot-icon"><svg width="34" height="34" viewBox="0 0 24 24" '
                f'fill="none" stroke="rgba(255,255,255,0.46)" stroke-width="1.4" '
                f'stroke-linecap="round" stroke-linejoin="round">'
                f'<rect x="3" y="5" width="18" height="14" rx="2"></rect>'
                f'<circle cx="8.5" cy="10" r="1.6"></circle>'
                f'<path d="m3 16 4.5-4 3.5 3 4-4.5L21 16"></path></svg></div>')
    return (f'<div class="slot {cls}" style="background: linear-gradient(148deg, {a} 0%, {b} 100%);'
            f' border-radius: {radius}px; {extra}">{fill}'
            f'<div class="slot-cap"><span class="slot-t">{caption}</span>'
            + (f'<span class="slot-chip">{ratio}</span>' if chip else '')
            + '</div></div>')


QUOTE_MARK = ('<path d="M9.5 5C6.4 5 4 7.5 4 10.6c0 2.7 1.9 4.8 4.4 4.8 1.2 0 2-.5 2-1.3 '
              '0-.7-.5-1.1-1.3-1.4-1.1-.4-1.7-1.1-1.7-2.1 0-1.4 1.1-2.4 2.6-2.4.5 0 .9.1 '
              '1.2.2V5.2C10.8 5.1 10.2 5 9.5 5Zm9 0C15.4 5 13 7.5 13 10.6c0 2.7 1.9 4.8 '
              '4.4 4.8 1.2 0 2-.5 2-1.3 0-.7-.5-1.1-1.3-1.4-1.1-.4-1.7-1.1-1.7-2.1 0-1.4 '
              '1.1-2.4 2.6-2.4.5 0 .9.1 1.2.2V5.2C19.8 5.1 19.2 5 18.5 5Z"/>')


# ======================================================================= desktop
def home():
    nav = ''.join(f'<a href="#" class="nav-a">{n}</a>' for n in NAV) + ''.join(
        f'<a href="#" class="nav-a" style="display: inline-flex; align-items: center; gap: 6px; '
        f'color: #8A7F85;">{lock()}{n}</a>' for n in GATED)

    mosaic = f"""<div style="position: relative; height: 470px;">
      {slot('m', 'Cultural evening', 'hero-cultural.jpg', cls='float-a',
            extra='position: absolute; left: 0; top: 10px; width: 262px; height: 338px;'
                  ' box-shadow: 0 22px 50px rgba(20, 8, 12, 0.42);')}
      {slot('g', 'Cricket', 'hero-cricket.jpg', cls='float-b',
            extra='position: absolute; right: 96px; top: 0; width: 214px; height: 214px;'
                  ' box-shadow: 0 22px 50px rgba(20, 8, 12, 0.42);')}
      {slot('p', 'Seminar', 'hero-seminar.jpg', cls='float-c',
            extra='position: absolute; right: 0; bottom: 16px; width: 252px; height: 226px;'
                  ' box-shadow: 0 22px 50px rgba(20, 8, 12, 0.42);')}
    </div>"""

    hero = f"""<div style="position: relative; background: {MAROON}; overflow: hidden;">
      <div style="position: absolute; left: -196px; bottom: -246px; opacity: 0.07;">
        {mark(620, '#FFFFFF', '#FFFFFF')}
      </div>
      <div style="position: absolute; left: 47%; top: 58px; width: 14px; height: 14px;
           border-radius: 50%; background: {GREEN};"></div>
      <div style="position: absolute; left: 41%; bottom: 118px; width: 9px; height: 9px;
           border-radius: 50%; background: #E9A8BC;"></div>
      <div class="wrap" style="position: relative; padding-top: 74px; padding-bottom: 150px;
           display: grid; grid-template-columns: minmax(0, 1fr) 524px; gap: 40px;
           align-items: center;">
        <div style="display: flex; flex-direction: column; gap: 23px;">
          <span class="eyebrow" style="color: #7FCB7C;">ENGINEERS FORUM QATAR</span>
          <h1 style="font-size: 51px; line-height: 1.1; color: #FFFFFF;">The apex body for
            <span style="color: {GREEN};">engineers of Kerala origin</span> working in Qatar.</h1>
          <p class="lede" style="color: #DDCBD2; max-width: 25em;">Eight hundred engineers, and a
            calendar that runs from the seminar room to the cricket ground to the stage.</p>
          <div style="display: flex; align-items: center; gap: 14px; padding-top: 4px;">
            <a href="#" class="btn btn-g">Apply to join</a>
            <a href="#" class="btn btn-ghost">Member sign in</a>
          </div>
          <div style="display: flex; align-items: flex-start; gap: 10px; padding-top: 2px;">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#7FCB7C"
                 stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"
                 style="flex-shrink: 0; margin-top: 2px;">
              <circle cx="12" cy="12" r="9"/><path d="m8 12.5 2.6 2.6L16 9.5"/></svg>
            <span style="font-size: 14.5px; line-height: 1.55; color: #C6AEB7;">Open to qualified
              engineers of Kerala origin resident in Qatar. The committee decides within five
              business days.</span>
          </div>
        </div>
        {mosaic}
      </div>
    </div>"""

    figs = [('800', 'members'), (SUPPLY, 'events a year'),
            (SUPPLY, 'years of EF'), (SUPPLY, 'colleges')]
    ftiles = ''.join(
        f"""<div style="display: flex; flex-direction: column; gap: 7px; align-items: center;
             {'border-left: 1px solid rgba(30, 51, 25, 0.18);' if k else ''}">
          {f'<span style="font-family: Quicksand, sans-serif; font-size: 46px; font-weight: 700; color: #16290F; line-height: 1;">{v}</span>'
             if v != SUPPLY else
             f'<div style="display: flex; align-items: center; height: 46px;"><span class="fig-tbc">{SUPPLY}</span></div>'}
          <span style="font-size: 14px; color: #23431C; font-weight: 700;">{label}</span>
        </div>""" for k, (v, label) in enumerate(figs))

    band = f"""<div class="wrap" style="margin-top: -70px; position: relative;">
      <div style="background: {GREEN}; border-radius: 20px; padding: 32px 36px;
           box-shadow: 0 18px 44px rgba(36, 16, 23, 0.17); display: grid;
           grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px;">{ftiles}</div>
    </div>"""

    pill = ''.join(f"""<div class="card" style="overflow: hidden; display: flex;
         flex-direction: column;">
      {slot(tone, cap, im, extra='height: 176px;', radius=0)}
      <div style="padding: 25px; display: flex; flex-direction: column; gap: 10px;">
        <h3 style="font-size: 21px;">{title}</h3>
        <p style="font-size: 14.5px; line-height: 1.68; color: #4A4045;">{body}</p>
      </div>
    </div>""" for tone, title, cap, im, body in PILLARS)

    gal = ''.join(slot(tone, cap, im, extra=f'grid-area: {area}; min-height: 200px;')
                  for tone, cap, im, area in GALLERY)

    gallery = f"""<div class="wrap">
      <div style="display: flex; align-items: flex-end; justify-content: space-between;
           gap: 32px; margin-bottom: 28px;">
        <div style="display: flex; flex-direction: column; gap: 12px;">
          <span class="eyebrow">LIFE AT EF</span>
          <h2 style="font-size: 34px; line-height: 1.18;">What a year at EF looks like</h2>
        </div>
        <a href="#" style="display: inline-flex; align-items: center; gap: 8px; font-size: 15px;
           font-weight: 700; white-space: nowrap;">The full gallery {arrow()}</a>
      </div>
      <div style="display: grid; grid-template-columns: repeat(4, minmax(0, 1fr));
           grid-auto-rows: 200px; gap: 18px;">{gal}</div>
    </div>"""

    quote = f"""<div class="wrap">
      <div style="background: #FFFFFF; border: 1px solid #D8E4F0; border-radius: 20px;
           padding: 44px 48px; display: grid; grid-template-columns: 54px minmax(0, 1fr);
           gap: 26px; align-items: start;">
        <svg width="54" height="54" viewBox="0 0 24 24" fill="{GREEN}"
             style="flex-shrink: 0;">{QUOTE_MARK}</svg>
        <div style="display: flex; flex-direction: column; gap: 18px;">
          <p style="font-family: Quicksand, sans-serif; font-size: 26px; line-height: 1.44;
             font-weight: 600; color: #241017; text-wrap: pretty;">A member quote belongs here —
            two or three lines on what EF has meant to them. It has to be a real member in their
            own words, collected and approved, not written for them.</p>
          <div style="display: flex; align-items: center; gap: 14px;">
            <img src="member-portrait.jpg" alt="" style="width: 52px; height: 52px; border-radius: 50%; object-fit: cover; display: block; flex-shrink: 0;">
            {tbc('Member name, category and year — EF to supply')}
          </div>
        </div>
      </div>
    </div>"""

    ann = ''.join(f"""<div class="card" style="padding: 28px; display: flex;
         flex-direction: column; gap: 13px;">
      <span style="font-size: 13px; color: #6E636A; font-weight: 600;">{date}</span>
      <h3 style="font-size: 19px; line-height: 1.35; text-wrap: pretty;">{title}</h3>
      <p style="font-size: 14.5px; line-height: 1.65; color: #4A4045;">{body}</p>
      <a href="#" style="display: inline-flex; align-items: center; gap: 7px; font-size: 14.5px;
         font-weight: 700; margin-top: 4px;">Read more {arrow()}</a>
    </div>""" for date, title, body in ANNOUNCEMENTS)

    evs = ''.join(f"""<div class="card" style="padding: 26px; display: flex; gap: 20px;
         align-items: center;">
      <div style="width: 68px; border-radius: 10px; overflow: hidden; text-align: center;
           flex-shrink: 0; border: 1px solid #D8E4F0;">
        <div style="background: {MAROON}; color: #FFFFFF; font-family: Quicksand, sans-serif;
             font-size: 11px; font-weight: 700; letter-spacing: 0.12em; padding: 6px 0;">{mon}</div>
        <div style="font-family: Quicksand, sans-serif; font-size: 27px; font-weight: 700;
             color: #241017; padding: 8px 0 10px;">{day}</div>
      </div>
      <div style="display: flex; flex-direction: column; gap: 7px; min-width: 0;">
        <h3 style="font-size: 17.5px; line-height: 1.35; text-wrap: pretty;">{name}</h3>
        <span style="font-size: 13.5px; color: #6E636A;">{time} · {tbc('Venue')}</span>
        <a href="#" style="display: inline-flex; align-items: center; gap: 7px; font-size: 14px;
           font-weight: 700; margin-top: 2px;">Register {arrow()}</a>
      </div>
    </div>""" for mon, day, name, time in EVENTS)

    bens = ''.join(f"""<div style="display: flex; flex-direction: column; gap: 13px;">
      <div style="width: 46px; height: 46px; border-radius: 12px; background: #E4F4E3;
           display: flex; align-items: center; justify-content: center;">
        {ic(icon, 23, '#2A7F26', 1.8)}</div>
      <h3 style="font-size: 18.5px;">{title}</h3>
      <p style="font-size: 14.5px; line-height: 1.7; color: #4A4045;">{body}</p>
    </div>""" for icon, title, body in BENEFITS)

    partner = f"""<div class="wrap">
      <div style="background: #E4F4E3; border-radius: 20px; padding: 44px 48px; display: grid;
           grid-template-columns: minmax(0, 1fr) 300px; gap: 52px; align-items: center;">
        <div style="display: flex; flex-direction: column; gap: 13px;">
          <span class="eyebrow">FOR PARTNERS</span>
          <h2 style="font-size: 30px; line-height: 1.2; text-wrap: pretty;">A partner can check
            an EF membership in seconds.</h2>
          <p style="font-size: 16px; line-height: 1.65; color: #3D4A3C; max-width: 40em;">
            The member shows their Digital ID; you see only what EF has configured for your
            partner type, and nothing more. It stops verifying the day their membership lapses.</p>
        </div>
        <div style="display: flex; flex-direction: column; gap: 16px; align-items: flex-start;">
          {tbc('Live partners — EF to supply')}
          <a href="#" class="btn btn-m">Become an EF partner</a>
        </div>
      </div>
    </div>"""

    offs = ''.join(f"""<div style="display: flex; flex-direction: column; gap: 8px;
         padding: 17px 0; border-top: 1px solid #E4EBF3;">
      <span style="font-size: 12px; color: #6E636A; font-weight: 700; letter-spacing: 0.07em;">
        {o.upper()}</span>
      {tbc('Name — EF to supply')}
    </div>""" for o in OFFICERS)

    gov = f"""<div class="wrap">
      <div style="display: grid; grid-template-columns: minmax(0, 1.3fr) minmax(0, 1fr);
           gap: 68px; align-items: start;">
        <div style="display: flex; flex-direction: column; gap: 21px;">
          <span class="eyebrow">GOVERNANCE</span>
          <h2 style="font-size: 34px; line-height: 1.18; text-wrap: pretty;">Run by an elected
            committee of volunteers.</h2>
          <p class="lede">Each officer holds office for a single term. The bylaws, the policies
            each committee works to, and the register of officers past and present are published
            here — because a professional body should be able to show it followed its own rules.</p>
          <div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr));
               gap: 0 40px;">{offs}</div>
          <div style="display: flex; align-items: center; gap: 26px; padding-top: 6px;">
            <a href="#" style="display: inline-flex; align-items: center; gap: 7px;
               font-size: 15px; font-weight: 700;">All officers {arrow()}</a>
            <a href="#" style="display: inline-flex; align-items: center; gap: 7px;
               font-size: 15px; font-weight: 700;">Bylaws and policies {arrow()}</a>
          </div>
        </div>
        <div class="card" style="padding: 30px; display: flex; flex-direction: column; gap: 15px;">
          <span style="font-size: 12px; color: #6E636A; font-weight: 700; letter-spacing: 0.07em;">
            AFFILIATION</span>
          <p style="font-size: 16px; line-height: 1.55; color: #241017; font-weight: 600;">
            Indian Business and Professional Council, under the Embassy of India in Qatar.</p>
          <p style="font-size: 14px; line-height: 1.65; color: #6E636A;">The affiliation raises
            the standard EF is held to on governance and on the handling of member data. The mark
            is shown only with the President's recorded permission.</p>
          {tbc('Affiliation mark — EF to supply')}
        </div>
      </div>
    </div>"""

    closing = f"""<div style="position: relative; background: {MAROON}; overflow: hidden;">
      <div style="position: absolute; right: -126px; top: -126px; opacity: 0.08;">
        {mark(520, '#FFFFFF', '#FFFFFF')}
      </div>
      <div class="wrap" style="position: relative; padding-top: 72px; padding-bottom: 72px;
           display: flex; align-items: center; justify-content: space-between; gap: 48px;">
        <div style="display: flex; flex-direction: column; gap: 11px;">
          <h2 style="font-size: 36px; line-height: 1.18; color: #FFFFFF;">Join eight hundred
            engineers.</h2>
          <p style="font-size: 16.5px; line-height: 1.6; color: #DDCBD2;">Apply once, and the
            committee decides within five business days.</p>
        </div>
        <a href="#" class="btn btn-g" style="height: 56px; padding: 0 34px; font-size: 16.5px;">
          Apply to join</a>
      </div>
    </div>"""

    cols = [('MEMBERSHIP', ['Who may join', 'Apply to join', 'Renew your membership',
                            'Member sign in']),
            ('GOVERNANCE', ['Bylaws', 'Policies', 'Privacy notice', 'Officers and terms']),
            ('COMMUNITY', ['Events', 'News', 'Become a partner', 'Post a vacancy'])]
    fcols = ''.join(
        f"""<div style="display: flex; flex-direction: column; gap: 13px;">
          <span style="font-family: Quicksand, sans-serif; font-size: 12px; color: #FFFFFF;
                font-weight: 700; letter-spacing: 0.13em; margin-bottom: 3px;">{h}</span>
          {''.join(f'<a href="#" style="font-size: 14.5px; color: #C6AEB7;">{i}</a>' for i in items)}
        </div>""" for h, items in cols)

    footer = f"""<div style="background: #3A1020;">
      <div class="wrap" style="padding-top: 56px; padding-bottom: 30px;">
        <div style="display: grid;
             grid-template-columns: minmax(0, 1.5fr) repeat(3, minmax(0, 1fr)); gap: 52px;">
          <div style="display: flex; flex-direction: column; gap: 19px;">
            {lockup(reversed_=True)}
            <p style="font-size: 14.5px; line-height: 1.7; color: #C6AEB7; max-width: 24em;">
              The apex body of engineers of Kerala origin working in the State of Qatar.</p>
            <div style="display: flex; flex-direction: column; gap: 8px; align-items: flex-start;">
              {tbc('Email — EF to supply')}
              {tbc('Address — EF to supply')}
            </div>
          </div>
          {fcols}
        </div>
        <div style="border-top: 1px solid #6B3040; margin-top: 46px; padding-top: 24px;
             display: flex; align-items: center; justify-content: space-between; gap: 24px;">
          <span style="font-size: 13px; color: #9A7883;">© 2027 Engineers Forum Qatar.</span>
          <span style="font-size: 13px; color: #9A7883;">Personal data held in the State of
            Qatar.</span>
        </div>
      </div>
    </div>"""

    def section(eyebrow, title, link, content, pad_top=90):
        return f"""<div class="wrap" style="padding-top: {pad_top}px;">
          <div style="display: flex; align-items: flex-end; justify-content: space-between;
               gap: 32px; margin-bottom: 28px;">
            <div style="display: flex; flex-direction: column; gap: 12px;">
              <span class="eyebrow">{eyebrow}</span>
              <h2 style="font-size: 34px; line-height: 1.18;">{title}</h2>
            </div>
            <a href="#" style="display: inline-flex; align-items: center; gap: 8px;
               font-size: 15px; font-weight: 700; white-space: nowrap;">{link} {arrow()}</a>
          </div>
          {content}
        </div>"""

    g3 = 'display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 24px;'

    body = f"""
  <div style="background: #2E0C19;">
    <div class="wrap" style="padding-top: 11px; padding-bottom: 11px; display: flex;
         align-items: center; justify-content: space-between; gap: 24px; font-size: 12.5px;">
      <span style="color: #B79AA4;">Affiliated to the Indian Business and Professional Council,
        under the Embassy of India in Qatar</span>
      <div style="display: flex; align-items: center; gap: 20px;">
        <a href="#" style="color: #B79AA4;">Contact EF</a>
        <span style="color: #6B3040;">|</span>
        <a href="#" style="color: #FFFFFF;">Member sign in</a>
      </div>
    </div>
  </div>

  <div style="background: #FFFFFF; border-bottom: 1px solid #E4EBF3;">
    <div class="wrap" style="padding-top: 20px; padding-bottom: 20px; display: flex;
         align-items: center; gap: 44px;">
      {lockup()}
      <div style="display: flex; align-items: center; gap: 28px; flex-grow: 1;">{nav}</div>
      <a href="#" class="btn btn-g" style="height: 44px; padding: 0 22px; font-size: 15px;">
        Apply to join</a>
    </div>
  </div>

  {hero}
  {band}

  {section('PROGRAMMES', 'Three sides to EF', 'All programmes',
           f'<div style="{g3}">' + pill + '</div>', pad_top=82)}

  <div style="padding-top: 90px;">{gallery}</div>

  {section('LATEST', 'What EF has announced', 'All news', f'<div style="{g3}">' + ann + '</div>')}
  {section('WHAT IS ON', 'Coming up', 'All events', f'<div style="{g3}">' + evs + '</div>')}

  <div style="padding-top: 90px;">{quote}</div>

  {section('MEMBERSHIP', 'What membership gives you', 'Who may join',
           '<div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));'
           ' gap: 42px 48px;">' + bens + '</div>')}

  <div style="padding-top: 90px;">{partner}</div>
  <div style="padding-top: 90px; padding-bottom: 94px;">{gov}</div>
  {closing}
  {footer}
"""
    return wrap_dc(body, 1440, 5820)


# ======================================================================== mobile
def home_mobile():
    hero = f"""<div style="position: relative; background: {MAROON}; overflow: hidden;">
      <div style="position: absolute; left: -142px; bottom: -162px; opacity: 0.08;">
        {mark(360, '#FFFFFF', '#FFFFFF')}
      </div>
      <div style="position: relative; padding: 32px 20px 42px; display: flex;
           flex-direction: column; gap: 19px;">
        <span class="eyebrow" style="color: #7FCB7C; font-size: 11.5px;">ENGINEERS FORUM
          QATAR</span>
        <h1 style="font-size: 32px; line-height: 1.14; color: #FFFFFF;">The apex body for
          <span style="color: {GREEN};">engineers of Kerala origin</span> working in Qatar.</h1>
        <p style="font-size: 15.5px; line-height: 1.65; color: #DDCBD2;">Eight hundred engineers,
          and a calendar that runs from the seminar room to the cricket ground to the stage.</p>
        <div style="display: grid; grid-template-columns: 1.4fr 1fr; gap: 10px;">
          {slot('m', 'Cultural evening', 'hero-cultural.jpg', extra='height: 162px;',
                radius=13, chip=False)}
          <div style="display: flex; flex-direction: column; gap: 10px;">
            {slot('g', 'Cricket', 'hero-cricket.jpg', extra='height: 76px;', radius=13,
                  chip=False)}
            {slot('p', 'Seminar', 'hero-seminar.jpg', extra='height: 76px;', radius=13,
                  chip=False)}
          </div>
        </div>
        <div style="display: flex; flex-direction: column; gap: 11px;">
          <a href="#" class="btn btn-g" style="width: 100%;">Apply to join</a>
          <a href="#" class="btn btn-ghost" style="width: 100%;">Member sign in</a>
        </div>
        <div style="display: flex; gap: 10px;">
          <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#7FCB7C"
               stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"
               style="flex-shrink: 0; margin-top: 2px;">
            <circle cx="12" cy="12" r="9"/><path d="m8 12.5 2.6 2.6L16 9.5"/></svg>
          <span style="font-size: 13.5px; line-height: 1.55; color: #C6AEB7;">Open to qualified
            engineers of Kerala origin resident in Qatar. The committee decides within five
            business days.</span>
        </div>
      </div>
    </div>"""

    band = f"""<div style="padding: 0 20px; margin-top: -26px; position: relative;">
      <div style="background: {GREEN}; border-radius: 16px; padding: 20px 22px;
           box-shadow: 0 14px 34px rgba(36, 16, 23, 0.18); display: flex;
           flex-direction: column; gap: 13px;">
        <div style="display: flex; align-items: baseline; gap: 11px;">
          <span style="font-family: Quicksand, sans-serif; font-size: 38px; font-weight: 700;
                color: #16290F; line-height: 1;">800</span>
          <span style="font-size: 14px; color: #23431C; font-weight: 700;">members on the
            register</span>
        </div>
        <div style="display: flex; flex-wrap: wrap; gap: 8px;
             border-top: 1px solid rgba(30, 51, 25, 0.2); padding-top: 13px;">
          <span class="fig-tbc">events a year</span>
          <span class="fig-tbc">years of EF</span>
          <span class="fig-tbc">colleges</span>
        </div>
      </div>
    </div>"""

    pill = ''.join(f"""<div class="card" style="overflow: hidden;">
      {slot(tone, cap, im, extra='height: 132px;', radius=0)}
      <div style="padding: 20px; display: flex; flex-direction: column; gap: 8px;">
        <h3 style="font-size: 18px;">{title}</h3>
        <p style="font-size: 14px; line-height: 1.65; color: #4A4045;">{body}</p>
      </div>
    </div>""" for tone, title, cap, im, body in PILLARS)

    gal = f"""<div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr));
         gap: 12px;">
      {slot('m', 'Cultural evening', 'gallery-cultural.jpg',
            extra='grid-column: span 2; height: 188px;')}
      {slot('g', 'Cricket tournament', 'gallery-cricket.jpg', extra='height: 148px;')}
      {slot('p', 'Technical seminar', 'gallery-seminar.jpg', extra='height: 148px;')}
    </div>"""

    ann = ''.join(f"""<div class="card" style="padding: 22px; display: flex;
         flex-direction: column; gap: 11px;">
      <span style="font-size: 12.5px; color: #6E636A; font-weight: 600;">{date}</span>
      <h3 style="font-size: 17.5px; line-height: 1.35;">{title}</h3>
      <p style="font-size: 14px; line-height: 1.65; color: #4A4045;">{body}</p>
      <a href="#" style="display: inline-flex; align-items: center; gap: 7px; font-size: 14px;
         font-weight: 700; margin-top: 2px;">Read more {arrow()}</a>
    </div>""" for date, title, body in ANNOUNCEMENTS[:2])

    evs = ''.join(f"""<div class="card" style="padding: 18px; display: flex; gap: 16px;
         align-items: center;">
      <div style="width: 58px; border-radius: 9px; overflow: hidden; text-align: center;
           flex-shrink: 0; border: 1px solid #D8E4F0;">
        <div style="background: {MAROON}; color: #FFFFFF; font-family: Quicksand, sans-serif;
             font-size: 10px; font-weight: 700; letter-spacing: 0.12em; padding: 5px 0;">{mon}</div>
        <div style="font-family: Quicksand, sans-serif; font-size: 22px; font-weight: 700;
             color: #241017; padding: 6px 0 8px;">{day}</div>
      </div>
      <div style="display: flex; flex-direction: column; gap: 5px; min-width: 0;">
        <h3 style="font-size: 16px; line-height: 1.35;">{name}</h3>
        <span style="font-size: 13px; color: #6E636A;">{time} · {tbc('Venue')}</span>
      </div>
    </div>""" for mon, day, name, time in EVENTS)

    bens = ''.join(f"""<div style="display: flex; gap: 15px;">
      <div style="width: 42px; height: 42px; border-radius: 11px; background: #E4F4E3;
           display: flex; align-items: center; justify-content: center; flex-shrink: 0;">
        {ic(icon, 21, '#2A7F26', 1.8)}</div>
      <div style="display: flex; flex-direction: column; gap: 6px; min-width: 0;">
        <h3 style="font-size: 16.5px;">{title}</h3>
        <p style="font-size: 14px; line-height: 1.65; color: #4A4045;">{body}</p>
      </div>
    </div>""" for icon, title, body in BENEFITS)

    def sect(eyebrow, title, content, link=None):
        more = (f'<a href="#" style="display: inline-flex; align-items: center; gap: 7px; '
                f'font-size: 14.5px; font-weight: 700;">{link} {arrow()}</a>') if link else ''
        return f"""<div style="padding: 40px 20px 0; display: flex; flex-direction: column;
             gap: 18px;">
          <div style="display: flex; flex-direction: column; gap: 9px;">
            <span class="eyebrow" style="font-size: 11.5px;">{eyebrow}</span>
            <h2 style="font-size: 25px; line-height: 1.2;">{title}</h2>
          </div>
          {content}{more}
        </div>"""

    body = f"""
  <div style="background: #FFFFFF; border-bottom: 1px solid #E4EBF3; padding: 14px 20px;
       display: flex; align-items: center; justify-content: space-between; gap: 16px;">
    {lockup()}
    <a href="#" style="width: 44px; height: 44px; display: flex; align-items: center;
       justify-content: center;">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#4B1728"
           stroke-width="2" stroke-linecap="round"><path d="M4 7h16M4 12h16M4 17h16"/></svg></a>
  </div>

  {hero}
  {band}

  {sect('PROGRAMMES', 'Three sides to EF',
        '<div style="display: flex; flex-direction: column; gap: 14px;">' + pill + '</div>')}
  {sect('LIFE AT EF', 'What a year at EF looks like', gal, 'The full gallery')}
  {sect('LATEST', 'What EF has announced',
        '<div style="display: flex; flex-direction: column; gap: 14px;">' + ann + '</div>',
        'All news')}
  {sect('WHAT IS ON', 'Coming up',
        '<div style="display: flex; flex-direction: column; gap: 12px;">' + evs + '</div>',
        'All events')}

  <div style="padding: 40px 20px 0;">
    <div class="card" style="padding: 26px 24px; display: flex; flex-direction: column;
         gap: 15px;">
      <svg width="40" height="40" viewBox="0 0 24 24" fill="{GREEN}">{QUOTE_MARK}</svg>
      <p style="font-family: Quicksand, sans-serif; font-size: 20px; line-height: 1.45;
         font-weight: 600; color: #241017;">A member quote belongs here — two or three lines on
        what EF has meant to them, in their own words, collected and approved.</p>
      <div style="display: flex; align-items: center; gap: 12px;">
        <img src="member-portrait.jpg" alt="" style="width: 52px; height: 52px; border-radius: 50%; object-fit: cover; display: block; flex-shrink: 0;">
        {tbc('Member name — EF to supply')}
      </div>
    </div>
  </div>

  {sect('MEMBERSHIP', 'What membership gives you',
        '<div style="display: flex; flex-direction: column; gap: 24px;">' + bens + '</div>')}

  <div style="padding: 40px 20px 0;">
    <div style="background: #E4F4E3; border-radius: 16px; padding: 26px 24px; display: flex;
         flex-direction: column; gap: 13px;">
      <span class="eyebrow" style="font-size: 11.5px;">FOR PARTNERS</span>
      <h2 style="font-size: 23px; line-height: 1.22;">A partner can check an EF membership in
        seconds.</h2>
      <p style="font-size: 14.5px; line-height: 1.65; color: #3D4A3C;">The member shows their
        Digital ID; you see only what EF has configured for your partner type, and nothing
        more.</p>
      <a href="#" class="btn btn-m" style="width: 100%; margin-top: 3px;">Become an EF
        partner</a>
    </div>
  </div>

  <div style="padding: 40px 20px 42px; display: flex; flex-direction: column; gap: 17px;">
    <div style="display: flex; flex-direction: column; gap: 9px;">
      <span class="eyebrow" style="font-size: 11.5px;">GOVERNANCE</span>
      <h2 style="font-size: 25px; line-height: 1.2;">Run by an elected committee of
        volunteers.</h2>
    </div>
    <p style="font-size: 15px; line-height: 1.7; color: #4A4045;">Each officer holds office for
      a single term. The bylaws, the policies each committee works to, and the register of
      officers past and present are published here.</p>
    <div style="display: flex; flex-direction: column; gap: 11px;">
      <a href="#" style="display: inline-flex; align-items: center; gap: 7px; font-size: 14.5px;
         font-weight: 700;">All officers {arrow()}</a>
      <a href="#" style="display: inline-flex; align-items: center; gap: 7px; font-size: 14.5px;
         font-weight: 700;">Bylaws and policies {arrow()}</a>
    </div>
  </div>

  <div style="position: relative; background: {MAROON}; overflow: hidden;">
    <div style="position: absolute; right: -92px; top: -92px; opacity: 0.08;">
      {mark(300, '#FFFFFF', '#FFFFFF')}
    </div>
    <div style="position: relative; padding: 36px 20px; display: flex; flex-direction: column;
         gap: 15px;">
      <h2 style="font-size: 27px; line-height: 1.18; color: #FFFFFF;">Join eight hundred
        engineers.</h2>
      <p style="font-size: 15px; line-height: 1.6; color: #DDCBD2;">Apply once, and the committee
        decides within five business days.</p>
      <a href="#" class="btn btn-g" style="width: 100%;">Apply to join</a>
    </div>
  </div>

  <div style="background: #3A1020; padding: 32px 20px 26px; display: flex;
       flex-direction: column; gap: 19px;">
    {lockup(reversed_=True)}
    <p style="font-size: 14px; line-height: 1.7; color: #C6AEB7;">The apex body of engineers of
      Kerala origin working in the State of Qatar.</p>
    <div style="display: flex; flex-wrap: wrap; gap: 10px 22px;">
      <a href="#" style="font-size: 14px; color: #C6AEB7;">Contact EF</a>
      <a href="#" style="font-size: 14px; color: #C6AEB7;">Bylaws</a>
      <a href="#" style="font-size: 14px; color: #C6AEB7;">Privacy notice</a>
      <a href="#" style="font-size: 14px; color: #C6AEB7;">Member sign in</a>
    </div>
    <span style="font-size: 12.5px; color: #9A7883; border-top: 1px solid #6B3040;
          padding-top: 18px;">© 2027 Engineers Forum Qatar. Personal data held in the State
      of Qatar.</span>
  </div>
"""
    return wrap_dc(body, 390, 6120)


def wrap_dc(body, w, h):
    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <script src="./support.js"></script>
</head>
<body>
<x-dc>
<helmet>
  {FONTS}
  <style>{CSS}  </style>
</helmet>

<div style="width: {w}px; background: {PALE};">{body}</div>
</x-dc>
<script data-dc-script data-props='{{"$preview":{{"width":{w},"height":{h}}}}}'>
class Component extends DCLogic {{}}
</script>
</body>
</html>
"""


if __name__ == '__main__':
    for name, html in [('Main.dc.html', home()), ('HomeMobile.dc.html', home_mobile())]:
        (HERE / name).write_text(html, encoding='utf-8')
        print('wrote', name, len(html), 'bytes')
